env:
  es2021: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:prettier/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  "prettier/prettier":
    [
      "error",
      {
        "semi": false,
        "singleQuote": true,
        "tabWidth": 2,
        "trailingComma": "all",
      },
    ]
